services:
  - type: web
    name: change-makers-museum
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python keep_alive.py & streamlit run app.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
